version: 0.56.4.{build}
configuration: Nightly
pull_requests:
  do_not_increment_build_number: true
build:
  project: GraySvr.vcxproj
  verbosity: minimal
after_build:
- cmd: mkdir accounts logs save scripts
- cmd: 7z a SphereSvr-Win32.zip accounts\ logs\ save\ scripts\ %APPVEYOR_BUILD_FOLDER%\%CONFIGURATION%\SphereSvr.exe %APPVEYOR_BUILD_FOLDER%\src\sphere.ini %APPVEYOR_BUILD_FOLDER%\src\sphereCrypt.ini %APPVEYOR_BUILD_FOLDER%\src\common\mysql\lib\libmysql.dll
artifacts:
- path: SphereSvr-Win32.zip
  name: SphereSvr